アルゴリズム、OTP桁数、タイムステップ数が変更できることの確認対応
ykws/OneTimePasswordExample pull request #10
Opened 2021-10-26 14:27 UTC by NMai-source

* [x] 対応する Issue が Linked Issues に設定されていることを確認してください

# 対応内容
ライブラリ OneTimePassword の仕様検証
アルゴリズム、OTP桁数、タイムステップ数が変更できることの確認

# スクリーンショット
| before | after |
|-------|------|
| ![simulator_screenshot_D0F25097-0852-466E-95E7-6F20C702E273](https://user-images.githubusercontent.com/84489601/139276822-062067a8-b34c-4bc0-9cfc-e867c8e5916a.png) | ![simulator_screenshot_6AF1B2B5-D58D-4B7F-B643-237CFE4A532E](https://user-images.githubusercontent.com/84489601/139275155-56af833c-3d82-4f68-a33e-98fd5d42fee4.png)|

Closes #2

2021-10-30 02:07 UTC, ykws requested changes
![must-badge](https://img.shields.io/badge/review-must-red.svg)
- rename
- アルゴリズム変更の反映
- タイムステップ数変更の描画反映

![next-badge](https://img.shields.io/badge/review-next-blueviolet)

- PR のタイトルは適切な内容で設定してほしいです。
- 設定画面に戻ると毎回設定がリセットされてしまい使いづらいので、TOP画面と設定画面では同じ値を参照するようにして欲しいです。
設定値はローカルに保存してしまっても良いと思います。

2021-10-30 02:07 UTC, ykws commented on OneTimePasswordExample/ViewController.m
> +        self.token.period = [_test3 intValue];
![must-badge](https://img.shields.io/badge/review-must-red.svg)

ワンタイムパスワードの生存時間を変更したら、描画処理も変更する必要があります。

ちょっと計算が処理が悩ましいのですが、
60秒の時は、30秒の半分の画面リフレッシュにすることで期待した結果になると思います。
`scheduledTimerWithTimeInterval` を `0.03` -> `0.06`

```obj-c
    [NSTimer scheduledTimerWithTimeInterval:0.06 target:self selector:@selector(updateOneTimePasswordView:) userInfo:nil repeats:YES];
```

2021-11-03 15:07 UTC, ykws commented on OneTimePasswordExample/SettingController.h
> +
@NMai-source 
**ViewController内の変数にセットする**のは SettingController 内なので、外部に公開しなくても参照可能です。

> この辺の記事を参考にしています。

リンクがないようです。

2021-11-05 13:36 UTC, ykws commented on OneTimePasswordExample/SettingController.m
> +-(void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

ViewController に SettingController の値を渡している箇所。
ここが SettingController 内なので、各 property を外部に公開する必要はないです。

2021-11-05 13:36 UTC, ykws commented on OneTimePasswordExample/SettingController.h
> +
@NMai-source 
コメントの誤字脱字を編集するのは良いですが、メッセージ内容を変えてしまうとコメントの時系列が前後してしまい、
内容を追いづらくなってしまうので、次からはコメントを新規に追加するようにお願いします。

> ViewController内の変数にセットする形で値を渡しているので、SettingControllerから変数にアクセスするのに@Propertyが必要かと思い、このように書きました。

ViewController 内の変数にセットするのは SettingController 内なので外部に公開する必要はないです。
property の定義は必要ですが、 public ではなく private で良いという意味です。

一方 ViewController の変数は SettingController から設定しているため、こちらは公開された状態で良いです。
（この2つを混同しているのかもと思い）

2021-11-09 06:05 UTC, NMai-source commented
@ykws 
お疲れ様です。
以下の指摘について、対応が完了しました。
> rename
> アルゴリズム変更の反映
> タイムステップ数変更の描画反映
> PR のタイトルは適切な内容で設定してほしいです。

以下の指摘についてはこれから修正予定です。
> 設定画面に戻ると毎回設定がリセットされてしまい使いづらいので、TOP画面と設定画面では同じ値を参照するようにして欲しいです。
> 設定値はローカルに保存してしまっても良いと思います。

2021-11-09 13:06 UTC, ykws approved these changes
指摘事項対応されていることを確認できました！

![LGTM](https://image.lgtmoon.dev/10989)

![next-badge](https://img.shields.io/badge/review-next-blueviolet)

コミットメッセージに以下のような記載は避けるようにしましょう。

> PR指摘事項対応

後からログを見た時に PR を知らないでも変更の意図がわかるようになっているのが望ましいです。

2021-11-09 13:06 UTC, ykws commented on OneTimePasswordExample/ViewController.m
> +        }
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

文字列よりも intValue から算出可能なので、以下のように求めつつ、プロパティにせずに直接 NSTimer に渡しても良さそうです。

```suggestion
        self.scheduledTimerWithTimeInterval = self.token.period / 1000;
```

2021-11-10 11:17 UTC, merged

2021-11-11 12:06 UTC, ykws commented
@NMai-source f9456f5 マージコミットが含まれてしまっているので、可能ならこのタイミングで rebase をするとログがより見やすくなります。

練習用のリポジトリを用意したので、この辺りの感覚を掴んでもらえると嬉しいです。

https://github.com/ykws/git-rebase-example

2021-11-11 13:49 UTC, NMai-source commented
@ykws 
マージコミットについて承知いたしました。
練習用のリポジトリについて、練習してみようと思ってできていないので、
issueを進めるのと並行してやろうと思います。