COCOAPODSバージョンアップ
ykws/OneTimePasswordExample pull request #11
Opened 2021-10-29 14:48 UTC by NMai-source

* [x] 対応する Issue が Linked Issues に設定されていることを確認してください

# 対応内容
COCOA PODSのバージョンを1.11.2にアップデートする対応

# スクリーンショット
**変更なし**

2021-10-30 02:11 UTC, ykws requested changes
![must-badge](https://img.shields.io/badge/review-must-red.svg)

他の変更が含まれているので、 main からライブラリ更新の branch を作成して PR の作成をお願いします。

2021-11-02 14:38 UTC, NMai-source commented
branchを作り直しました。
ご確認よろしくお願いいたします。

2021-11-02 23:51 UTC, ykws commented
@NMai-source こちらも #12 と同様です。（参考リンクなど載せているのでそちらを参照願います）

<img width="1237" alt="Screen Shot 2021-11-03 at 8 48 39" src="https://user-images.githubusercontent.com/5770480/139967139-30eaa215-927d-4371-89e8-e28f1bebf6e0.png">

こちらの PR に対する一例です。

```
git switch -c feature-updateCocoapods-new upstream:main
git cherry-pick 46a5c0325b02d681d079b177679c60313d598702
```

2021-11-03 06:01 UTC, NMai-source commented
@ykws 
こちらのPRについても修正いたしました。
お手数ですが、ご確認よろしくお願いいたします。

2021-11-03 14:33 UTC, ykws approved these changes
対応ありがとうございます！

![LGTM](https://image.lgtmoon.dev/71393)

2021-11-10 05:13 UTC, merged