設定画面のテキストを全て表示する対応
ykws/OneTimePasswordExample pull request #12
Opened 2021-10-29 15:01 UTC by NMai-source

* [x] 対応する Issue が Linked Issues に設定されていることを確認してください

# 対応内容
設定画面のテキストを全て表示する対応
トークン表示画面のテキスト表示調節対応

# スクリーンショット
| before | after |
|-------|------|
|![simulator_screenshot_994C0A30-ACD8-4988-8ACD-B70E401415DF](https://user-images.githubusercontent.com/84489601/139457475-50ec0571-02bc-479c-a6d0-6c06c3695fae.png)| ![simulator_screenshot_3A5C01FC-2C22-4EAB-B301-7286B17CDEEA](https://user-images.githubusercontent.com/84489601/139456735-bb87cd6b-5a6a-4ad6-89d0-053702baa9ff.png)| 
|-------|------|
|![simulator_screenshot_3DE4B6FF-D818-43EE-99C4-3D822AD35968](https://user-images.githubusercontent.com/84489601/139457406-2de09708-c922-43fa-890b-badd1aa8a22e.png)|![simulator_screenshot_C6522044-980B-4029-87DA-16846A314B3A](https://user-images.githubusercontent.com/84489601/139456601-433b69c8-60ee-4c51-8089-b6f889bc3bbf.png)|

Closes #9

2021-10-30 02:12 UTC, ykws requested changes
![must-badge](https://img.shields.io/badge/review-must-red.svg)

内容はばっちりです！
ただし、こちらも他の変更が含まれているため、 main から branch を作成して、この課題の変更のみで PR を作成してください。

2021-11-02 14:28 UTC, NMai-source commented
branchを作り直しました。
ご確認よろしくお願いいたします。

2021-11-02 23:48 UTC, ykws commented
@NMai-source 赤枠のコミットだけがこの課題の変更に該当すると思うので、この PR のコミットはこれだけになっているのが望ましいです。

<img width="1233" alt="Screen Shot 2021-11-03 at 8 42 48" src="https://user-images.githubusercontent.com/5770480/139966716-28ff8cf0-cd60-4f04-9fc0-6074cd81614c.png">

今回のケースだと、一例ですが、 [cherry-pick](https://git-scm.com/docs/git-cherry-pick) を利用すると実現しやすそうです。

```
git switch -c feature-#9-new upstream:main
git cherry-pick 33ffe00ffde4a92b8c0253abc16070c8e86dd203
```

## 参考
- [git cherry-pick でいいとこ取り！【連載】マンガでわかるGit ～コマンド編～](https://www.r-staffing.co.jp/engineer/entry/20200327_1)

2021-11-03 05:43 UTC, NMai-source commented
@ykws 
すみません、対象のコミットを勘違いしていました。
cherrypickについて参考記事ありがとうございます。
参考にしてコミットを整理します。

2021-11-03 05:58 UTC, NMai-source commented
@ykws 
修正しました。
何度もすみませんが、ご確認よろしくお願いいたします。

2021-11-03 14:56 UTC, ykws commented on OneTimePasswordExample/Base.lproj/Main.storyboard
> +                                                <constraint firstAttribute="width" relation="lessThanOrEqual" constant="170" id="fvy-zA-QbD"/>
![must-badge](https://img.shields.io/badge/review-must-red.svg)

直前の制約と重なる部分があるので見直しをお願いします。
以下、制約の警告が確認できるので、この警告には対応するようにお願いします。

赤矢印の指す、黄色の矢印のアイコンをクリックすると、制約の警告を確認できます。

<img width="369" alt="Screen Shot 2021-11-03 at 23 44 26" src="https://user-images.githubusercontent.com/5770480/140084165-1d5435c9-9642-443a-976f-40d14dc5147e.png">

クリックした後の警告表示

<img width="746" alt="Screen Shot 2021-11-03 at 23 44 06" src="https://user-images.githubusercontent.com/5770480/140084289-8f26aace-01dd-4b9c-8d28-7c30f79bba08.png">

2021-11-11 12:16 UTC, ykws approved these changes
全て表示できるようになっていることを確認できました！

スクリーンショットも見やすくて良いです！

最新の main を rebase してこの PR をマージしてみてください。

2021-11-11 12:18 UTC, ykws commented
> 最新の main を rebase してこの PR をマージしてみてください。

⬇️ GitHub 上で「Update branch」をクリックしても良いですが、マージコミットが作成されてしまう気がします。

<img width="838" alt="Screen Shot 2021-11-11 at 21 17 28" src="https://user-images.githubusercontent.com/5770480/141296694-41942aae-3195-4b3c-b7a2-3bc4c6770344.png">

2021-11-11 14:07 UTC, NMai-source commented
@ykws 
mainをrebaseでマージしました。

2021-11-12 00:45 UTC, ykws commented
@NMai-source ばっちりです！　GitHub 上でマージできるようになっているのでそのままマージして大丈夫です！

<img width="663" alt="Screen Shot 2021-11-12 at 9 45 02" src="https://user-images.githubusercontent.com/5770480/141389411-7e6f8b4a-0465-4d94-a9e7-22415279f75a.png">

2021-11-12 14:57 UTC, merged

2021-11-12 14:58 UTC, NMai-source commented
@ykws 
すみません、マージまでしたつもりになっていました。
マージ完了しました。